### ISSUE TITLE
When binding json-data to a data property that is an array of objects, csv is showing extra column

### ISSUE THREAD

**Issue by sbell9** [angeliquekom/vue-json-to-csv#2]
When I bind json-data to a data property that is an array of objects and then export the csv, I'm seeing an extra column with the label _obj_ present. Each row in that column under the label is [object Object]. 

Example:

In my template:
`<vue-json-to-csv :json-data="test_export" :csv-title="'transactions'">`

In the data function of my component:
`              data: function () {
            return {
                test_export: [{name: 'Joe', surname: 'Roe'}, {name: 'Joe', surname: 'Doe'}]};},
`

And result when exporting:

<img width="222" alt="screen shot 2018-07-20 at 11 39 28 am" src="https://user-images.githubusercontent.com/18508420/43014372-9ac4a226-8c11-11e8-94c8-a9424f03723f.png">

This is only happening when binding to an array in my component's data. If I have the json-data binded to in-line (not sure what the correct terminology is) data like in your examples, it works perfectly, but that isn't feasible for what I'm trying to do.

**Comment by angeliquekom** [comment]
Thank you very much for your bug report! This error was caused due to handling a vue.js object as a normal object (observer object was involved at the parsing of values). I tried to get only the values needed using destructuring assignment (https://github.com/vuejs/Discussion/issues/292). I have published a new version at NPM, 1.0.5. Please let me know if that solves your problem.

**Comment by sbell9** [comment]
Fix looks like it works, thank you for the response
